version: 2
jobs:
  build:
    parallelism: 1
    docker:
      - image: circleci/ruby:2.6.3-stretch-node-browsers-legacy
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          PGHOST: 127.0.0.1
          PGUSER: do_be_have
          RAILS_ENV: test
      - image: circleci/postgres:9.6.14-alpine-ram
        environment:
          POSTGRES_USER: do_be_have
          POSTGRES_DB: do_be_have_test
          POSTGRES_PASSWORD: ""
      - image: redis:4.0
      - image: memcached:1.5.16-alpine
    environment:
      - DATABASE_URL: "postgres://do_be_have@localhost:5432/do_be_have_test"
      - SENDGRID_API_KEY: "fake_key"
      - COVERAGE: "true"

    steps:
      - checkout

      - run:
          name: Which bundler?
          command: gem install bundler

      # Restore bundle cache
      - restore_cache:
          keys:
            - do_be_have-bundle-v1-{{ checksum "Gemfile.lock" }}
            - do_be_have-bundle-v1-

      - run:
          name: Bundle Install
          command: bundle check || bundle install

      # Store bundle cache
      - save_cache:
          key: do_be_have-bundle-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      # Restore yarn cache
      - restore_cache:
          keys:
            - yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-cache-{{ .Branch }}
            - yarn-cache

      - run: yarn install

      # Store yarn cache
      - save_cache:
          key: yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      - run:
          name: Wait for Postgres
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Update Apt
          command: sudo apt-get update

      - run:
          name: Install PostgresClient
          command: sudo apt install postgresql-client-common postgresql-client-9.6

      - run:
          name: Install Chrome
          command: |
            wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
            sudo apt-get update
            sudo apt-get -y install google-chrome-stable

      - run:
          name: Database setup
          command: bundle exec rake db:schema:load --trace

      - run:
          name: Compile Webpacker Assets
          command: bundle exec rails webpacker:compile


      # Run rspec
      - run:
          name: "Run Tests"
          command: |
            bundle exec rspec --color \
                              --profile 10 \
                              --format RspecJunitFormatter \
                              --out test_results/rspec.xml \
                              --format progress \
                              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)

      # Save test results for timing analysis
      - store_test_results:
          path: test_results
